services:
  node:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: npm install
  # mongodb
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --auth
